/** Dev International brand + product catalogue */

export const brand = {
  name: "Dev International",
  shortName: "Dev",
  tagline: "Specialty Chemicals",
  description:
    "One stop for a wide range of quality chemicals at competitive prices and timely service. Trusted specialty chemicals supplier since 1995.",
  url: "https://www.devinternational.in",
  logo: "/images/brand/logo.png",
  email: {
    primary: "devesh@devinternational.in",
    sales: "sales@devinternational.in",
  },
  phones: ["+91 98925 42200", "+91 79778 67728", "+91 90295 77220", "+91 80977 32200"],
  whatsapp: "https://wa.me/919892542200",
  address: {
    line1: "A-302, Blue Bell, Royal Complex",
    line2: "Eksar Road, Borivali West",
    city: "Mumbai - 400 092",
    country: "India",
    full: "A-302, Blue Bell, Royal Complex, Eksar Road, Borivali West, Mumbai - 400 092, India",
  },
  warehouse: "Well-equipped godown at Bhiwandi (central location)",
  founder: {
    name: "Devesh Mehta",
    role: "Founder & CEO",
    bio: "Devesh Mehta, Founder and CEO of Dev International, has been in the chemical field for decades. His experience and devotion have led the company to prosper.",
  },
  established: "1995",
} as const;

export type Product = {
  slug: string;
  title: string;
  short: string;
  href: string;
  image: string;
  blurb: string;
  items: string[];
};

export const products: Product[] = [
  {
    slug: "oleo-derivatives",
    title: "Oleo Derivatives",
    short: "Oleo & specialty ingredients",
    href: "/products/oleo-derivatives",
    image: "/images/brand/product-oleo.webp",
    blurb:
      "A comprehensive portfolio of oleo derivatives and specialty ingredients for cosmetics, personal care, and industrial formulations.",
    items: [
      "Sophorolipid",
      "Body Wax",
      "Specialty Emulsifiers",
      "Specialty Ingredients",
      "Secondary Ingredients",
      "Preservatives · Antimicrobials · Biocides",
      "Mild Surfactants",
      "Hair Colour Protection Molecule",
      "Concentrated Blend",
      "Diluted Blend",
      "Lip Balm",
      "Polyquaternium 7",
      "GINOQUAT HPC",
      "GINOMOL ST",
      "Behenyl Alcohol based Ethoxylate",
      "Cetearyl alcohol and Ceteareth 20",
      "Cetearyl alcohol and Ceteareth-30",
      "Cetearyl alcohol and Polysorbate 60",
      "Cetearyl alcohol and Sodium Alkyl Sulphate",
      "Emulsifying Wax",
      "2-Ethyl Hexyl Palmitate-Stearate",
      "2-Ethyl Hexyl Palmitate",
      "Butyl Oleate",
      "Butyl Stearate",
      "Caprylic Capric Triglyceride",
      "Cetearyl Octanoate",
      "Cetyl Acetate",
      "Cetyl Octanoate",
      "Cetyl Palmitate",
      "Di Octyl Maleate",
      "Ethylhexyl Palmitate and IPM",
      "Glycerol Di Stearate",
      "Glycerol Mono Stearate",
      "Isopropyl Myristate (IPM)",
      "Isopropyl Palmitate (IPP)",
      "Isohydroxy Stearate and IPM",
      "Isopropyl 12 Hydroxy Stearate",
      "Methyl Laurate",
      "Mixture of Cetearyl Octanoate & 2-EHP",
      "Myristyl Myristate",
      "Octyl Hydroxy Stearate",
      "PEG Distearate",
      "Tridecyl Palmitate",
      "Tridecyl Salicylate",
      "Coco Amido Propyl Betaine (CAPB)",
      "Coco Betaine",
      "Disodium Laureth Sulfosuccinate (DELSS)",
      "Disodium Lauryl Sulfosuccinate (DLSS)",
      "Lauryl Amine Oxide",
      "Sodium Lauryl Sulfoacetate",
      "Benzalkonium Chloride",
      "Dodecyl Guanidine Hydrochloride",
      "Mixed Glycerides & Sophorolipids",
      "Phenoxyethanol",
      "Soap Noodles",
      "Ceteareth-12",
      "Ceteareth-20",
      "Ceteareth-25",
      "Steareth-2",
      "Steareth-20",
    ],
  },
  {
    slug: "fatty-acids",
    title: "Fatty Acids",
    short: "Industrial fatty acids",
    href: "/products/fatty-acids",
    image: "/images/brand/product-fatty-acids.webp",
    blurb:
      "High-quality fatty acids for soaps, detergents, rubber, plastics, cosmetics, and specialty chemical manufacturing.",
    items: [
      "12-Hydroxy Stearic Acid",
      "Behenic Acid",
      "Caprylic Acid",
      "Caprylic Capric Acid",
      "Distilled Coconut Fatty Acid",
      "Linseed Fatty Acid",
      "Stearic Acid 60%",
      "Lauric Acid",
      "Stearic Acid 90%",
      "Myristic Acid",
      "Oleic Acid",
      "Palm Fatty Acid",
      "Palm Kernel Fatty Acid",
      "Palmitic Acid",
      "Rice Bran Fatty Acid",
      "Ricinoleic Acid",
      "Soya Fatty Acid",
      "Stearic Acid (Stearic Content Min 70%)",
      "Stearic Acid Cosmetic Grade",
      "Stearic Acid Polymer Grade",
      "Stearic Acid Rubber Grade",
    ],
  },
  {
    slug: "oleic-acid",
    title: "Oleic Acid",
    short: "Oleic acid grades",
    href: "/products/oleic-acid",
    image: "/images/brand/product-oleic-acid.webp",
    blurb:
      "Specialty oleic acid grades for cosmetics, lubricants, textiles, and chemical intermediates.",
    items: [
      "Oleic 75%",
      "Lubolic 20/E",
      "Indolic Acid",
      "Emulsolic Capric Acid",
      "Lopour Acid",
      "Liquolic RBS",
    ],
  },
  {
    slug: "stearic-acid",
    title: "Stearic Acid",
    short: "Stearic acid grades",
    href: "/products/stearic-acid",
    image: "/images/brand/product-stearic-acid.webp",
    blurb:
      "Stearic acid across cosmetic, polymer, rubber, and specialty grades, supplied for formulations demanding consistent purity.",
    items: [
      "Stearic Content Min 90%",
      "Stearic Acid Cosmetic Grade",
      "Stearic Acid Polymer Grade",
      "Stearic Acid Rubber Grade",
      "Stearic Acid Specialty Grade",
    ],
  },
  {
    slug: "fatty-alcohol",
    title: "Fatty Alcohol",
    short: "Fatty alcohols range",
    href: "/products/fatty-alcohol",
    image: "/images/brand/product-fatty-alcohol.webp",
    blurb:
      "Fatty alcohols used as emollients, thickeners, and intermediates across personal care and industrial applications.",
    items: [
      "Behenyl Alcohol",
      "Ceto Stearyl Alcohol",
      "Cetostearyl Alcohol 50-50 Mole",
      "Cetyl Alcohol",
      "Lauryl Alcohol",
      "Myristyl Alcohol",
      "Oleyl Cetyl Alcohol",
      "Stearyl Alcohol",
      "C8 Alcohol (Octanol)",
      "C10 Alcohol (Decyl Alcohol)",
      "C8/C10 Alcohol (Octyl Decyl Alcohol)",
    ],
  },
  {
    slug: "fatty-esters",
    title: "Fatty Esters",
    short: "Esters for formulations",
    href: "/products/fatty-esters",
    image: "/images/brand/product-esters.webp",
    blurb:
      "A broad range of fatty esters for cosmetics, lubricants, plastics, and specialty formulations.",
    items: [
      "Potassium Caprylate",
      "Sodium Caprylate",
      "Monolauryl Disodium Succinate",
      "Sodium Lactate",
      "Di Glycol Mono Laurate",
      "Glycerol Mono Laurate",
      "Potassium Laurate",
      "Potassium Myristate",
      "Sodium Myristate",
      "Cetyl Octanoate",
      "Ammonium Oleate",
      "Butyl Oleate",
      "Glycerol Mono Oleate",
      "Polyethylene Glycol Mono Oleate",
      "Potassium Oleate",
      "Sodium Oleate",
      "Sulphated Methyl Oleate",
      "Trimethylolpropane Tri Oleate (TMPTO)",
      "Octyl 2-Ethyl Hexyl Palmitate",
      "Potassium Palmitate",
      "Sodium Palmitate",
      "Potassium Ricinoleate",
      "Sodium Ricinoleate",
      "Aluminium Stearate",
      "Ammonium Stearate",
      "Barium Stearate",
      "Butyl Stearate",
      "Cadmium Stearate",
      "Calcium Stearate",
      "Cetostearyl Stearate",
      "Cetyl Stearate",
      "Ethylene Glycol Di Stearate (EGDS)",
      "Ethylene Glycol Mono Stearate (EGMS)",
      "Glyceryl Stearate (and) PEG-100 Stearate",
      "Iso Butyl Stearate",
      "Magnesium Stearate",
      "Octyl 2-Ethyl Hexyl Palmitic Stearate",
      "Polyethylene Glycol Mono Stearate",
      "Potassium Stearate",
      "Sodium Stearate",
      "Stearyl Stearate",
      "Zinc Stearate",
      "Glycerol Trioleate",
      "Glycerol Tristearate",
      "Coco Diethanolamide (CDEA)",
      "Coco Monoethanolamide (CMEA)",
      "Lauramide DEA",
      "PEG 130 Distearate 6000",
      "Polyethylene Glycol 7 Glyceryl Cocoate",
      "Propylene Glycol Mono Myristate / Stearate",
    ],
  },
  {
    slug: "glycerin",
    title: "Glycerin",
    short: "Refined glycerin grades",
    href: "/products/glycerin",
    image: "/images/brand/product-glycerin.webp",
    blurb:
      "Refined glycerin grades for pharmaceutical, food, cosmetic, and industrial use.",
    items: [
      "Glycerin BP",
      "Glycerin CP",
      "Glycerin EP",
      "Glycerin IP",
      "Glycerin USP",
      "Glycerin IW",
      "Refined Glycerin",
    ],
  },
  {
    slug: "wax",
    title: "All Type of Wax",
    short: "Industrial & cosmetic waxes",
    href: "/products/wax",
    image: "/images/brand/product-wax.webp",
    blurb:
      "A full spectrum of natural and synthetic waxes for cosmetics, packaging, coatings, and industrial applications.",
    items: [
      "Beeswax",
      "Emulsifying Wax",
      "Caprylic Acid",
      "Caprylic Capric Acid",
    ],
  },
  {
    slug: "phosphorous",
    title: "Phosphorous Compounds",
    short: "Phosphorous chemistry",
    href: "/products/phosphorous",
    image: "/images/brand/product-phosphorous.webp",
    blurb:
      "Phosphorous compounds and related chemistries for water treatment, metal pretreatment, and specialty applications.",
    items: [
      "Cresyl Di-Phenyl Phosphate",
      "Tri Butyl Phosphate",
      "Tri Cresyl Phosphate",
      "Tri Nonylphenyl Phosphite",
      "Tri Phenyl Phosphate",
    ],
  },
  {
    slug: "amines-phosphates-sulphites",
    title: "Amines, Phosphates & Sulphites",
    short: "Amines and inorganic phosphates",
    href: "/products/amines-phosphates-sulphites",
    image: "/images/brand/product-amines.webp",
    blurb:
      "Amines, inorganic phosphates, and sulphites for water treatment, metal pretreatment, and specialty chemical processes.",
    items: [
      "Lauryl Di Methyl Amine",
      "Coco Di Methyl Amine",
      "Stearyl Amine",
      "Coco Amine",
      "Oleyl Amine",
      "EO PO-61",
      "EO PO-62",
      "EO PO-64",
      "Tetra Sodium Pyro Phosphate",
      "Potassium Pyro Phosphate",
      "Sodium Tri Poly Phosphate",
      "Potassium Tri Poly Phosphate",
      "Sodium Bi Sulphite",
      "Meta Bi Sulphite",
    ],
  },
  {
    slug: "solvent-esters",
    title: "Solvent Esters",
    short: "Solvents & esters",
    href: "/products/solvent-esters",
    image: "/images/brand/product-solvent.webp",
    blurb:
      "Solvent esters for paints, inks, coatings, adhesives, and industrial cleaning formulations.",
    items: [
      "Butyl Acetate",
      "Butyl Carbitol Acetate",
      "Butyl Cellosolve Acetate",
      "Butyl Propionate",
      "Ethyl Acetate",
      "Ethyl Carbitol Acetate",
      "Ethyl Cellosolve Acetate",
      "Iso Butyl Acetate",
      "Methoxy Butyl Acetate",
      "Methoxy Propyl Acetate",
      "Methoxy Propyl Propionate",
      "Methyl Cellosolve Acetate",
      "Propylene Glycol Di Acetate (PGDA)",
      "Triacetin",
    ],
  },
  {
    slug: "surfactants",
    title: "Surfactants",
    short: "Mild & specialty surfactants",
    href: "/products/surfactants",
    image: "/images/brand/product-surfactants.webp",
    blurb:
      "Alpha olefin sulphonates, sodium lauryl sulphates, and ether sulphates for detergents, shampoo, textile, and industrial cleaning.",
    items: [
      "Alpha Olefin Sulphonate Liquid (Detergent)",
      "Alpha Olefin Sulphonate Paste",
      "Sodium Lauryl Sulphate Liquid (Natural based)",
      "Sodium Lauryl Sulphate Needles",
      "Sodium Lauryl Sulphate Needles (Natural based)",
      "Sodium Lauryl Sulphate Paste (Natural based)",
      "Sodium Lauryl Sulphate Powder",
      "Alpha Olefin Sulphonate Refined",
      "Alpha Olefin Sulphonate Needles",
      "Alpha Olefin Sulphonate Powder",
      "Alpha Olefin Sulphonate Liquid (Shampoo)",
      "Alpha Olefin Sulphonate Liquid (Textile)",
      "Sodium Lauryl Ether Sulphate Liquid",
      "Sodium Lauryl Ether Sulphate Paste",
    ],
  },
  {
    slug: "various-mole-ethoxylates",
    title: "Various Mole Ethoxylates",
    short: "Ethoxylates of all categories",
    href: "/products/various-mole-ethoxylates",
    image: "/images/brand/product-ethoxylates.webp",
    blurb:
      "PEG grades and ethoxylates of alcohols, phenols, acids, amines, and oils, across all mole ranges for industrial and formulation use.",
    items: [
      "PEG-200",
      "PEG-300",
      "PEG-400",
      "PEG-600",
      "PEG-1500",
      "PEG-4000",
      "PEG-6000",
      "Lauryl Alcohol Ethoxylate",
      "Octyl Phenol Ethoxylate",
      "Nonyl Phenol Ethoxylate",
      "Tri Decyl Alcohol Ethoxylate",
      "Castor Oil Ethoxylate",
      "Hydrogenated Castor Oil Ethoxylate",
      "Coconut Ethoxylate",
      "Pureoleic Ethoxylate",
      "Lauric Acid Ethoxylate",
      "Stearic Acid Ethoxylate",
      "Oleic Acid Ethoxylate",
      "Coco Amine Ethoxylate",
      "Stearyl Amine Ethoxylate",
      "Oleyl Amine Ethoxylate",
    ],
  },
  {
    slug: "vegetable-oil",
    title: "Vegetable Oil",
    short: "Natural & modified vegetable oils",
    href: "/products/vegetable-oil",
    image: "/images/brand/product-vegetable-oil.webp",
    blurb:
      "Epoxidized, hydrogenated, and natural vegetable oils for plasticisers, lubricants, coatings, and specialty applications.",
    items: [
      "Epoxidized Soya Oil (ESO)",
      "Hydrogenated Palm Oil (HPO)",
      "Hydrogenated Castor Oil (HCO)",
      "Hydrogenated Soya Oil (HSO)",
      "Linseed Oil",
      "Rapeseed Oil",
      "Corn Oil",
      "Castor Oil",
      "Mustard Oil",
      "Cotton Seed Oil",
    ],
  },
  {
    slug: "more-products",
    title: "More Products",
    short: "Additional specialty products",
    href: "/products/more-products",
    image: "/images/brand/product-more.webp",
    blurb:
      "Soap noodles, casein, metallic soaps, essential oils, and additional specialty chemicals beyond our core portfolio.",
    items: [
      "Soap Noodles",
      "Casein",
      "LA, All Mole Ethoxylates",
      "Laurate",
      "Palmitate",
      "Myristate",
      "Stearate",
      "Oleate",
      "Riconilate",
      "Essential Oil",
    ],
  },
];

export const applications = [
  "Cosmetic",
  "Pharmaceutical",
  "Skin Care Products",
  "Bathing Soap Products",
  "Home Care Cleaning",
  "Food",
  "Paint",
  "Ink / Printing Ink",
  "Resin",
  "Varnish",
  "Adhesive & Glues",
  "Adhesive Tapes",
  "Plastic Industry",
  "Rubber",
  "Textile Industries",
  "Paper",
  "Carbon Paper",
  "Aluminium Foil",
  "Cable",
  "Wood and Laminates",
  "Construction Chemical",
  "Water Treatment",
  "Metal Treatment Chemical",
  "Cutting Oil",
  "Foundry Chemical",
  "Dyes & Intermediates",
  "Oil Field",
  "Ointment",
  "Cough Syrup",
  "Metallic Stearate Products",
  "Alkyd Resin Products",
  "Specialty Chemical",
] as const;

export const applicationImages: Record<string, string> = {
  "Carbon Paper": "/images/application/Carbon_paper.webp",
  "Construction Chemical": "/images/application/Construction_chemical_.webp",
  "Cough Syrup": "/images/application/CoughSyrup.webp",
  Food: "/images/application/Food.webp",
  Varnish: "/images/application/varnisnew1.webp",
  "Home Care Cleaning": "/images/application/Home_cxare_cleaning_.webp",
  "Plastic Industry": "/images/application/Plastic_Ind.webp",
  "Textile Industries": "/images/application/Textile_Industries.webp",
  Paper: "/images/application/Paper_.webp",
  "Water Treatment": "/images/application/Water_treatment_.webp",
  "Oil Field": "/images/application/oil_feild_.webp",
  "Ink / Printing Ink": "/images/application/PRINTING_INK.webp",
  Rubber: "/images/application/RUBBERnew.webp",
  Cosmetic: "/images/application/COSMETIC.webp",
  "Cutting Oil": "/images/application/CUTTING_OIL.webp",
  "Dyes & Intermediates": "/images/application/DYES_&_INTERMEDIATES.webp",
  "Foundry Chemical": "/images/application/FOUNDRY_CHEMICAL.webp",
  "Metal Treatment Chemical": "/images/application/METAL_TREATMENT_CHEMICAL1.webp",
  Ointment: "/images/application/OINTMENT3.webp",
  Paint: "/images/application/PAINT.webp",
  Pharmaceutical: "/images/application/PHARMACEUTICAL.webp",
  Resin: "/images/application/RESIN_2.webp",
  "Specialty Chemical": "/images/application/SPECIALITY_CHEMICAL_2.webp",
  "Wood and Laminates": "/images/application/WOOD.webp",
  "Adhesive & Glues": "/images/application/ADHESIVE_&_GLUES.webp",
  "Adhesive Tapes": "/images/application/ADHESIVE_TAPES3.webp",
  "Aluminium Foil": "/images/application/ALUMINIUM_FOIL2.webp",
  Cable: "/images/application/CABLE3.webp",
  "Skin Care Products": "/images/application/scanproduct.webp",
  "Bathing Soap Products": "/images/application/Bathing_soap.webp",
  "Metallic Stearate Products": "/images/application/metalic_sterate.webp",
  "Alkyd Resin Products": "/images/application/acrylated_alkyd_resin.webp",
};

export const industries = [
  "Building & Construction",
  "Plastics & Packaging",
  "Water & Health",
  "Food & Pharma",
  "Automotive",
  "Electronics",
  "Renewable Energies",
  "Cosmetics & Personal Care",
  "Rubber & Cable",
  "Paints, Inks & Resins",
  "Adhesives & Glues",
  "Dyes, Pigments & Intermediates",
] as const;

export const stats = [
  { value: 1995, suffix: "", label: "Established", sub: "Three decades of chemical supply" },
  { value: 9, suffix: "+", label: "Product Lines", sub: "Oleo to surfactants under one roof" },
  { value: 30, suffix: "+", label: "Industries Served", sub: "Cosmetics to construction" },
  { value: 500, suffix: "+", label: "Active Clients", sub: "MNCs, MSMEs & trade houses" },
] as const;

export const process = [
  {
    n: "01",
    title: "Enquiry & Specification",
    body: "Share your grade, quantity, and application. Our team maps the requirement to the right product and source within hours.",
    tag: "Day 0",
  },
  {
    n: "02",
    title: "Sourcing & Quotation",
    body: "We draw from vetted manufacturers and our stocked inventory to quote competitive pricing with clear lead times.",
    tag: "Day 1-2",
  },
  {
    n: "03",
    title: "Quality Assurance",
    body: "Each lot is checked against agreed specifications and supported with COA / TDS documentation before dispatch.",
    tag: "Day 2-3",
  },
  {
    n: "04",
    title: "Dispatch & Logistics",
    body: "Packed, labelled, and shipped from our Bhiwandi warehouse, coordinated for timely delivery across India.",
    tag: "Day 3-5",
  },
  {
    n: "05",
    title: "After-Sales Support",
    body: "Technical follow-up, repeat-order scheduling, and dedicated account management for long-term partners.",
    tag: "Ongoing",
  },
] as const;

export const certifications = [
  { name: "ISO 9001", desc: "Quality management" },
  { name: "Good Manufacturing Practice", desc: "Pharma-grade handling" },
  { name: "REACH Compliant", desc: "EU import standards" },
  { name: "Cosmos Approved Sources", desc: "Cosmetic ingredients" },
  { name: "FDA Compliant Grades", desc: "Food-contact materials" },
  { name: "RSPO Mass Balance", desc: "Sustainable palm" },
] as const;

export const testimonials = [
  {
    quote:
      "Dev International has been our reliable partner for oleo derivatives for years. Consistent quality and on-time delivery, every single time.",
    name: "Head of Procurement",
    role: "Cosmetic Manufacturer",
    location: "Mumbai",
  },
  {
    quote:
      "Their range under one roof saves us multiple supplier negotiations. Pricing is transparent and competitive across grades.",
    name: "Operations Director",
    role: "Specialty Chemicals Unit",
    location: "Vapi",
  },
  {
    quote:
      "We trust their technical team to recommend the right surfactant for our formulation. Real expertise, not just trading.",
    name: "R&D Manager",
    role: "Home Care Brand",
    location: "Bhiwandi",
  },
] as const;

export const team = [
  {
    name: brand.founder.name,
    role: brand.founder.role,
    bio: brand.founder.bio,
    focus: "Strategy & Key Accounts",
  },
  {
    name: "Sales & Technical Team",
    role: "Customer Engagement",
    bio: "Trained professionals managing enquiries, quotations, and technical recommendations across all product lines.",
    focus: "Enquiry to Dispatch",
  },
  {
    name: "Warehouse & Logistics",
    role: "Supply Operations",
    bio: "Dedicated staff at the Bhiwandi godown handling packing, quality checks, and dispatch coordination.",
    focus: "Bhiwandi Godown",
  },
] as const;

export const faqs = [
  {
    q: "What is the minimum order quantity?",
    a: "MOQ varies by product and grade. For most oleo derivatives and surfactants we support drum to tanker quantities. Contact us with your requirement and we will confirm MOQ and pricing.",
  },
  {
    q: "Do you provide COA and TDS documents?",
    a: "Yes. Every dispatched lot ships with a Certificate of Analysis and Technical Data Sheet from the manufacturer. Additional documentation is available on request.",
  },
  {
    q: "Which geographies do you serve?",
    a: "We supply across India from our Mumbai office and Bhiwandi warehouse. We also support export enquiries for select grades, confirm with our sales team for your destination.",
  },
  {
    q: "Can you supply custom or blended grades?",
    a: "Yes. For select product lines we work with manufacturers to supply custom blends and specifications. Share your formulation need and our technical team will evaluate feasibility.",
  },
  {
    q: "What are your payment terms?",
    a: "Standard terms are mutually agreed based on order size, customer relationship, and credit profile. First orders are typically advance; established accounts get credit terms on approval.",
  },
  {
    q: "How quickly can you dispatch?",
    a: "Stocked items from our Bhiwandi godown dispatch within 1-3 working days. Make-to-order or tanker loads follow the manufacturer lead time, which we confirm at quotation.",
  },
] as const;

export const sustainabilityPillars = [
  {
    title: "Bio-based Feedstock",
    body: "We prioritise oleochemicals derived from renewable plant oils, palm, coconut, and soya, reducing dependence on petrochemical inputs.",
  },
  {
    title: "Mass Balance Sourcing",
    body: "Where available we offer RSPO Mass Balance certified grades, supporting segregated sustainable palm supply chains.",
  },
  {
    title: "Responsible Logistics",
    body: "Consolidated dispatch from our central Bhiwandi warehouse cuts repeated transport legs and the emissions per delivery.",
  },
  {
    title: "Documentation & Traceability",
    body: "Full COA, TDS, and origin documentation on every lot, so your sustainability claims are backed by verifiable records.",
  },
] as const;
